powerhouse-inc/document-engineering

src/scalars/components/boolean-field/boolean-field.stories.tsx

https://trello.com/c/alKl1wl3/995-create-a-read-only-diff-status-for-the-boolean-component
- Should the new status allow to see the diff given the additions and removals

fix(scalars): add props in boolean scalars

---

src/ui/components/data-entry/toggle/subcomponents/toogle-diff.tsx
src/ui/components/data-entry/toggle/toggle.tsx

https://trello.com/c/wAmbLyTg/1004-add-the-boolean-read-only-diff-status-to-the-document-types
Should add the read only diff status in the Unified/Read Only

fix(scalars): fix the type and pass mixed in the toogle

---

src/ui/components/data-entry/date-time-picker/use-date-time-picker.tsx

https://trello.com/c/gQD0Heue/1013-date-fields-should-not-allow-letters
DateTimeField should allow letters only for the specified formats.  **Current Output:** The field always allows letters.

feat(scalars): add validation in the date-time-field component

---

src/ui/components/data-entry/date-picker/utils.ts
src/ui/components/data-entry/date-time-picker/use-date-time-picker.tsx

https://trello.com/c/gQD0Heue/1013-date-fields-should-not-allow-letters
Still pending with default format:Environment: DateTimeField **Expected Output:** DateTimeField should allow letters only for the specified formats. The field always allows letters.  **Vis

fix(scalars): fix date-time when not format is set

---

src/ui/components/data-entry/date-picker/utils.ts

https://trello.com/c/dQU8XrOb/1012-cant-start-typing-in-the-country-selector-before-clicking
- Check don't allow letters in some formats in connect

fix(scalars): allow numbers in date format in connet

---

src/ui/components/data-entry/date-picker/date-picker.tsx

https://trello.com/c/UXaSGUbg/1026-the-date-picker-number-font-doesnt-change-colour-on-selection-apart-from-current-date-so-the-date-selected-is-unreadable
- Should apply the proper style for the selected date

fix(scalars): add the important rule to avoid override styles

---

src/ui/components/data-entry/date-picker/subcomponents/calendar/calendar.tsx

https://trello.com/c/UXaSGUbg/1026-the-date-picker-number-font-doesnt-change-colour-on-selection-apart-from-current-date-so-the-date-selected-is-unreadable
- Should apply the proper style for the selected date

fix(scalars): allow show correct the value select from the calendar

---

src/scalars/components/fragments/id-autocomplete/use-id-autocomplete.ts

https://trello.com/c/F9R8s73V/990-fix-the-flickering-in-the-phid-when-is-an-array
- Should ensure that the PHID works properly after inserting a value that match an initial option.

fix(scalars): add missing dependencies to useEffect in use-id-autocomplete hook

---

src/scalars/components/number-field/number-field.test.tsx
src/ui/components/data-entry/number-input/use-number-input.ts

https://trello.com/c/iV03PjGR/757-9-amountfield
Fixed precision issues in number input when using decimal steps. JavaScript's IEEE 754 floating-point representation can cause small imprecisions in decimal arithmetic (e.g., 1235 + 0.2 resulting in 1235.2000000000003 instead of 1235.2).
Implemented proper decimal precision handling in the number input component by:
- Using `toFixed` with the specified precision to ensure consistent decimal places
- Maintaining the same precision as the step value when no precision is specified
- Adding test coverage to verify correct decimal handling

fix(scalars): fix the step when its decimal point

---

src/scalars/components/amount-field/amount-field-validations.ts

https://trello.com/c/iV03PjGR/757-9-amountfield
A duplications errors appears when the field its required in the amountField component
- Remove unnecessary check for when value its undefined:

fix(scalars): remove duplicate message in amount-field validations

---

src/scalars/components/url-field/url-field.stories.tsx
src/ui/components/data-entry/input/subcomponent/text-diff.tsx
src/ui/components/data-entry/url-input/types.ts
src/ui/components/data-entry/url-input/url-input-diff.tsx
src/ui/components/data-entry/url-input/url-input.stories.tsx
src/ui/components/data-entry/url-input/url-input.tsx

https://trello.com/c/iS9Q3Gns/1052-fix-urlinput-diff-display-when-basevalue-and-value-are-equal-and-non-empty
- fix issue when the URL inputs in diff mode doesn't show any value when the base value and the value are equals
- removed option of diff mode in URL as there's only one mode and it doesn't make sense to have it anymore

fix: url diff mode when the original value and the value are equals

---

src/ui/components/data-entry/amount-input/utils.ts

https://trello.com/c/iV03PjGR/757-9-amountfield
– When the trailingZeros prop is enabled, trailing zeros are not retained in the input display after the onBlur event.

fix(scalars): allow show the ceros, when trailingZeros its set

---

src/scalars/components/country-code-field/country-code-field.stories.tsx
src/scalars/components/enum-field/enum-field.stories.tsx
src/scalars/components/enum-field/enum-field.tsx
src/ui/components/data-entry/country-code-picker/country-code-picker-diff.tsx
src/ui/components/data-entry/country-code-picker/country-code-picker.stories.tsx
src/ui/components/data-entry/country-code-picker/country-code-picker.test.tsx
src/ui/components/data-entry/country-code-picker/country-code-picker.tsx
src/ui/components/data-entry/country-code-picker/types.ts
src/ui/components/data-entry/select/content.tsx
src/ui/components/data-entry/select/select-diff.tsx
src/ui/components/data-entry/select/select.stories.tsx
src/ui/components/data-entry/select/select.test.tsx
src/ui/components/data-entry/select/select.tsx
src/ui/components/data-entry/select/types.ts

https://trello.com/c/F6f4scJh/1032-create-a-read-only-diff-status-for-the-countrycode-component
- Should fix diff status in Select component.
- Should add the necessary props and types to display the new diff status in CountryCodePicker & CountryCodeFied.
- Should the new status allow to see the diff given the additions and removals.

feat(scalars & ui): add diff status to CountryCodePicker & CountryCodeField components

---

src/scalars/components/aid-field/aid-field.stories.tsx
src/scalars/components/currency-code-field/currency-code-field.stories.tsx
src/scalars/components/fragments/id-autocomplete/id-autocomplete-diff.tsx
src/scalars/components/fragments/id-autocomplete/id-autocomplete-list-option.tsx
src/scalars/components/fragments/id-autocomplete/id-autocomplete.tsx
src/scalars/components/fragments/id-autocomplete/types.ts
src/scalars/components/fragments/id-autocomplete/use-id-autocomplete.ts
src/ui/components/data-entry/aid-input/__snapshots__/aid-input.test.tsx.snap
src/ui/components/data-entry/aid-input/aid-input.stories.tsx
src/ui/components/data-entry/aid-input/aid-input.test.tsx
src/ui/components/data-entry/aid-input/aid-input.tsx
src/ui/components/data-entry/aid-input/types.ts
src/ui/components/data-entry/currency-code-picker/currency-code-picker.stories.tsx
src/ui/components/data-entry/oid-input/types.ts
src/ui/components/data-entry/phid-input/types.ts

https://trello.com/c/xfUYBkwa/1059-create-a-read-only-diff-status-for-the-aid-component
- Should add tests to AIDInput.
- Should add the necessary props and types to display the new status.
- Should the new status allow to see the diff given the additions and removals.

feat(scalars & ui): add diff status to AIDInput & AIDField

---

src/scalars/components/date-picker-field/__snapshots__/date-picker-field.test.tsx.snap
src/scalars/components/date-time-picker-field/__snapshots__/date-time-picker-field.test.tsx.snap
src/scalars/components/time-picker-field/__snapshots__/time-picker-field.test.tsx.snap
src/ui/components/data-entry/date-picker/__snapshots__/date-picker.test.tsx.snap
src/ui/components/data-entry/date-picker/date-picker.tsx
src/ui/components/data-entry/date-time-picker/__snapshots__/date-time-picker.test.tsx.snap
src/ui/components/data-entry/date-time-picker/base-picker.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.tsx
src/ui/components/data-entry/date-time-picker/utils.ts
src/ui/components/data-entry/time-picker/__snapshots__/time-picker.test.tsx.snap
src/ui/components/data-entry/time-picker/time-picker.tsx
src/ui/components/data-entry/time-picker/use-time-picker.ts
src/ui/components/data-entry/time-picker/utils.test.ts
src/ui/components/data-entry/time-picker/utils.ts

- https://trello.com/c/HnZVa4UX/1063-add-month-year-and-year-only-selection-modes-to-the-datepicker
- Should support a mode that lets users pick only a month and a year.

fix(scalars): fix focus label and fix unnecessary props

---

src/scalars/components/date-time-picker-field/__snapshots__/date-time-picker-field.test.tsx.snap
src/ui/components/data-entry/date-time-picker/__snapshots__/date-time-picker.test.tsx.snap
src/ui/components/data-entry/date-time-picker/subcomponent/date-time-picker-diff.tsx
src/ui/components/data-entry/date-time-picker/use-date-time-picker.tsx
src/ui/components/data-entry/date-time-picker/utils.test.ts
src/ui/components/data-entry/date-time-picker/utils.ts
src/ui/components/data-entry/time-picker/time-picker.test.tsx
src/ui/components/data-entry/time-picker/use-time-picker.ts
src/ui/components/data-entry/time-picker/utils.ts

- https://trello.com/c/SMGtrk6b/795-3-datetimefield-date-datetime-time
- The error "Invalid date format. Use undefined" appears when the time and date values are swapped — e.g., 12:20 2025-06-22 instead of the expected 2025-06-22 12:20.
- When a date is set via the defaultValue parameter for the DateTimePicker field, the time is displayed with seconds (HH:mm:ss) on page load or refresh, which does not match the expected HH:mm format and fails validation.

fix(scalars): apply default format to value in date-time-picker

---

src/scalars/components/date-time-picker-field/date-time-picker-field-validations.ts
src/ui/components/data-entry/date-time-picker/use-date-time-picker.tsx
src/ui/components/data-entry/date-time-picker/utils.ts

https://trello.com/c/SMGtrk6b/795-3-datetimefield-date-datetime-time
- When a value with an incorrect format passes through the value, it should show an error message (2025-02-01 10:23), Its not a valid ISO format when it's passed in the value field
- In the DateTime Field. Inserting time and date, e.g., 12:30 2025-08-12, and click outside/Submit. The error message related to the invalid format should appear. Initially, a message related to the date is visible, and after a few seconds, the error message changes.

fix(scalars): add validations for invalid values

---

src/scalars/components/fragments/text-field/text-field.test.tsx
src/scalars/components/string-field/string-field.stories.tsx
src/ui/components/data-entry/text-input/text-input.stories.tsx
src/ui/components/data-entry/text-input/text-input.tsx
src/ui/components/data-entry/textarea/textarea.stories.tsx
src/ui/components/data-entry/textarea/textarea.tsx

https://trello.com/c/oxAOKsO1/1072-diff-status-comparison-stories-are-missing-in-multiples-components
- Should the diff comparison status for Strings be reflected as stories.

fix(scalars): add missing stories for the string component

---

src/scalars/components/url-field/url-field.stories.tsx
src/scalars/components/url-field/url-field.test.tsx
src/ui/components/data-entry/url-input/url-input-diff.tsx
src/ui/components/data-entry/url-input/url-input.stories.tsx
src/ui/components/data-entry/url-input/url-input.tsx

- https://trello.com/c/oxAOKsO1/1072-diff-status-comparison-stories-are-missing-in-multiples-components
- Should the diff comparison status for URL be reflected as stories? Add some for the difference  and test the component

fix(scalars): add missing stories for url and add test for diff

---

src/scalars/components/date-time-picker-field/date-time-picker-field-validations.ts
src/scalars/components/date-time-picker-field/date-time-picker-field.stories.tsx
src/ui/components/data-entry/date-picker/subcomponents/month-grid.tsx
src/ui/components/data-entry/date-picker/use-date-picker.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker-content.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.tsx
src/ui/components/data-entry/date-time-picker/use-date-time-picker.tsx
src/ui/components/data-entry/date-time-picker/utils.ts

- https://trello.com/c/HnZVa4UX/1063-add-month-year-and-year-only-selection-modes-to-the-datepicker
- The new date formats (YYYY-MM, MM/YYYY, MMM-YYYY, 2025-06, 06/2025, JUN-2025) should be visible for the DateTime picker.

feat(scalars): add new format for the date-time-picker

---

src/ui/components/data-entry/amount-input/use-amount-input.tsx
src/ui/components/data-entry/currency-code-picker/currency-code-picker.tsx

- https://trello.com/c/Y2sFr9aM/1086-storybook-breaks-after-adding-a-currency-name
- Should the field works properly when a currency name is added in the prop. Add the moment for the story book, add new currency without correct type, broken the UI.

fix(scalars): filter values that had ticker and cripto properties

---

src/scalars/components/email-field/email-field.stories.tsx
src/scalars/components/email-field/email-field.test.tsx
src/ui/components/data-entry/email-input/email-input.stories.tsx
src/ui/components/data-entry/email-input/email-input.tsx
src/ui/components/data-entry/email-input/types.ts

https://trello.com/c/Hl5iClSo/1078-16-email
- Read only - diff comparison status  stories
- Should set the **Default** as a String/Null. ( A default email value if one is provided, or null if there is no default)
- Should ensure the Value is the current email address entered by the user, or null if not set. Validate the email

feat(scalars): add diff for simple value in email component

---

src/scalars/components/email-field/__snapshots__/email-field.test.tsx.snap
src/scalars/components/email-field/email-field.stories.tsx
src/scalars/components/email-field/email-field.test.tsx
src/scalars/components/email-field/email-field.tsx
src/scalars/components/email-field/utils.ts
src/scalars/components/form/form.test.tsx
src/scalars/components/form/form.tsx
src/scalars/lib/validators/validateFieldMatch.ts
src/ui/components/data-entry/email-input/email-input.tsx

https://trello.com/c/Hl5iClSo/1078-16-email
- Allow validate a field base in other field throw the matchFieldName props
- Should ensure that the component can be used inside and outside of the form context.
- Should an email confirmation field be requested if **showEmaildConfirmation** is true.

feat(scalars): add field match function and add test

---

src/scalars/components/email-field/email-field.tsx
src/scalars/components/id-field/id-field.tsx

- https://trello.com/c/Hl5iClSo/1078-16-email
- Submitting the value several time, only once is reflected (Connect) . Fix the IdField, to generate a new id, in each submit

fix(scalars): fix submit id in id-field correct-way get id email

---

src/scalars/components/email-field/email-field.stories.tsx
src/scalars/components/email-field/email-field.tsx

https://trello.com/c/Hl5iClSo/1078-16-email
The maxLenght and/or minLenght prop set. * After cleaning the prop, the field should no longer validate against the prop value set before. The field validates against the prop value even after it was cleaned.  The props are no correct add to the field

fix(scalars): pass min and max values to field

---

src/ui/components/dropdown-menu/dropdown-menu.tsx
src/ui/components/object-set-table/logic/table-api.ts
src/ui/components/object-set-table/logic/types.ts
src/ui/components/object-set-table/subcomponents/cells/information-cell.tsx
src/ui/components/object-set-table/subcomponents/rows/render-row.tsx
src/ui/components/object-set-table/subcomponents/rows/row-actions.tsx

https://trello.com/c/aWCV973N/1037-apply-deletion-functionality-to-the-objectsettable
- Remove the delete icon in the information column when the rows are hovered
- Add a "Delete" secondary action if the table allows deletions
- Add a "Delete x selected rows" secondary actions when there are multiple rows selected, allowing to delete all selected rows at once
- Fix insertions
- Add configurable options to the delete function in the table API

feat(table): move delete options to the secondary row actions

---

src/ui/components/sidebar/sidebar.test.tsx
src/ui/components/sidebar/subcomponents/sidebar-item.tsx
src/ui/components/sidebar/types.ts

https://trello.com/c/8TO462mo/1112-document-types-created-are-represented-with
- Should ensure that the node is by default created with the placeholder: Doc No - Name

fix(altas): add placeholder for document without number and name

---

src/ui/components/data-entry/password-input/password-strength.tsx
src/ui/components/data-entry/password-input/utils.ts

https://trello.com/c/vaeTU0JQ/1124-indicate-when-password-requirements-are-met-within-the-password-component
- Adds a color transition when a password suggestion is met

feat(ui): add color transition when a password suggestion is met

---

src/ui/components/data-entry/number-input/number-input.test.tsx
src/ui/components/data-entry/number-input/number-input.tsx

https://trello.com/c/PDs76XV9/1151-internal-error-when-the-value-default-value-is-defined-in-the-number-input
- Should ensure that the component doesn't trigger any error when the values are defined.

fix(scalars): avoid warning caused by using both value and defaultValue

---

src/ui/components/data-entry/amount-input/amount-input.test.tsx
src/ui/components/data-entry/amount-input/use-amount-input.tsx

-  After interacting with the "units" field (which was previously inactive), a TypeError: options. Some is not a function error occurs. The AmountCurrency (or other amount) component fails to render properly. **Steps to reproduce:** 1. Open amy amount (e.g. AmountCurrency) component in Storybook 2. Activate the "units" field 3. Error appears immediately after interaction.

fix(scalars): fix the units error

---

src/ui/components/sidebar/subcomponents/sidebar-item.tsx

https://trello.com/c/2EjkcZti/1169-allow-sidebar-selected-node-to-have-a-bg-color
- Should apply a bg-color for the selected node. [design]

feat(scalars): add background and color to the selected node

---

src/ui/components/data-entry/password-input/password-input.tsx

https://trello.com/c/45k6gQ8u/1168-eye-icon-should-be-disabled-if-password-component-is-disabled
- Fix disabled state on PasswordInput component (Should ensure the eye icon is not interactive when the field is disabled)

fix(ui): disabled state on PasswordInput

---

src/scalars/components/aid-field/__snapshots__/aid-field.test.tsx.snap
src/scalars/components/fragments/id-autocomplete/__snapshots__/id-autocomplete.test.tsx.snap
src/scalars/components/fragments/id-autocomplete/id-autocomplete-input-container.tsx
src/scalars/components/fragments/id-autocomplete/use-id-autocomplete.ts
src/scalars/components/oid-field/__snapshots__/oid-field.test.tsx.snap
src/scalars/components/phid-field/__snapshots__/phid-field.test.tsx.snap
src/ui/components/data-entry/aid-input/__snapshots__/aid-input.test.tsx.snap
src/ui/components/data-entry/oid-input/__snapshots__/oid-input.test.tsx.snap
src/ui/components/data-entry/phid-input/__snapshots__/phid-input.test.tsx.snap

https://trello.com/c/gjHqTmQV/1159-input-focus-lost-after-autocomplete-result-found-in-phid-oid-aid-fields
- Fix focus on IdAutocomplete based fields (Should the focus not be removed after showing the result list)

fix(scalars & ui): focus on IdAutocomplete based fields

---

src/ui/components/sidebar/__snapshots__/sidebar.test.tsx.snap
src/ui/components/sidebar/sidebar.stories.tsx
src/ui/components/sidebar/sidebar.tsx
src/ui/components/sidebar/subcomponents/sidebar-header.tsx
src/ui/components/sidebar/subcomponents/sidebar-item.tsx
src/ui/components/sidebar/subcomponents/sidebar-pinning-area.tsx

https://trello.com/c/2EjkcZti/1169-allow-sidebar-selected-node-to-have-a-bg-color
- Allow to pass custom classes to customize items from the sidebar

feat(scalars): add custom class for styled the sideBar

---

src/table/logic/table-api.ts

https://trello.com/c/GUb4sSsU
- When trying to save elements in the "adding row", it detected the values as empty and it didn't save/created new elements. Now, it is fixed
- After adding a value, the form is reset so next time the user have a cleared form

fix(table): saving non empty values was detected as empty

---

src/table/components/table-focus-trap.tsx
src/table/hooks/useGlobalTableKeyEvents.tsx
src/table/logic/selection-manager.ts
src/table/logic/table-api.ts

https://trello.com/c/GUb4sSsU
- Fix focus loss after the edition ends or the user clicks outside the table while editing

fix(table): focus loss after edition exit

---

src/scalars/components/fragments/select-field/select-field.test.tsx
src/ui/components/data-entry/select/select.test.tsx
src/ui/components/data-entry/select/select.tsx
src/ui/components/data-entry/select/use-select.ts

https://trello.com/c/1LBnPVC1/1184-drop-down-components-across
- Maintain selection when re-selecting the same option in the Select component when !multiple && !searchable

fix(select): maintain selection when re-selecting the same option

---

src/scalars/components/fragments/textarea-field/textarea-field.test.tsx
src/table/components/default-cell-editors/get-cell-editor-fn.ts
src/table/components/default-cell-renderers/get-render-fn.ts
src/table/components/default-cell-renderers/string-multiline-render.tsx
src/table/components/default-cell-renderers/string-render.tsx
src/table/components/default-fns/default-column-config.ts
src/table/components/default-sort-columns/default-sort-fns.ts
src/table/docs/col-definition.mdx
src/table/table/types.ts
src/ui/components/data-entry/textarea/textarea.tsx

https://trello.com/c/7Q389yX6/939-create-default-editor-render-for-components-types-objectsettable
- Improve the default String editor and renderer (adds support for multiline strings)
- Fix cursor positioning in the Textarea when it is auto focused

fix(table): improve string default editor & renderer

---

src/table/components/table-provider/table-reducer.tsx
src/table/docs/events.mdx
src/table/events/index.ts
src/table/events/table-event-manager.ts
src/table/events/types.ts
src/table/examples/events/events.tsx
src/table/logic/table-api.ts

https://trello.com/c/1ig4QoYK/1054-add-selection-event-listeners-to-objectsettable-rows
This PR adds comprehensive event support for table sort state changes, enabling applications to listen and respond to sorting events in the table component.
- **Table Reducer**: Enhanced `table-reducer.tsx` with sort state change handling and event triggering
- **Event System**: Extended event types and manager in `table-event-manager.ts` and `types.ts` to support sort events
- **Documentation**: Updated `events.mdx` with comprehensive documentation for the new sort event functionality
- **Examples**: Enhanced `events.tsx` example to demonstrate sort event handling
- **API Integration**: Minor updates to `table-api.ts` for proper event integration
- **Export Updates**: Updated `index.ts` to export new …

feat(table): add event support for sort state changes
