src/ui/components/data-entry/toggle/subcomponents/toogle-diff.tsx
src/ui/components/data-entry/toggle/toggle.tsx

https://trello.com/c/wAmbLyTg/1004-add-the-boolean-read-only-diff-status-to-the-document-types
- Should add the read only diff status in the Split/Read Only

fix(scalars): add disable props and export ToggleBaseProps

---

src/ui/components/data-entry/toggle/subcomponents/toogle-diff.tsx

https://trello.com/c/wAmbLyTg/1004-add-the-boolean-read-only-diff-status-to-the-document-types
Should add the read only diff status in the Unified/Read Only

fix(scalars): add representation addition o delete in mixed state

---

src/ui/components/data-entry/toggle/subcomponents/toogle-diff.tsx

https://trello.com/c/wAmbLyTg/1004-add-the-boolean-read-only-diff-status-to-the-document-types
Should add the read only diff status in the Unified/Read Only

fix(scalars): fix color in correct label

---

src/scalars/components/phid-field/phid-field.tsx

https://trello.com/c/opniEnpF
- Support any PHID format

feat: support any phid ID format

---

src/scalars/components/url-field/url-field.stories.tsx
src/scalars/components/url-field/url-field.tsx
src/ui/components/data-entry/input/splitted-input-diff.tsx
src/ui/components/data-entry/input/subcomponent/text-diff.tsx
src/ui/components/data-entry/url-input/url-favicon.tsx
src/ui/components/data-entry/url-input/url-input-diff.tsx
src/ui/components/data-entry/url-input/url-input.stories.tsx
src/ui/components/data-entry/url-input/url-input.tsx
src/ui/components/index.ts

https://trello.com/c/dZTkwG4q/986-create-a-read-only-diff-status-for-the-url-component
- Should add the expected props.
- Should allow to see the diff given the additions/removals and changes.
- Should add to the existing component the new status Read Only Diff (Storybook variant).

feat(scalars & ui): add diff support to URLInput & URLField

---

src/scalars/components/form/forms.mdx
src/scalars/components/index.ts
src/scalars/docs/getting-started.mdx
src/ui/components/dropdown/dropdown.stories.tsx

https://trello.com/c/etmzxfat
- Remove old references to the design-system library
- Improve getting started doc

docs: improve getting started

---

src/ui/components/object-set-table/mock-data.ts
src/ui/components/object-set-table/object-set-table.stories.tsx
src/ui/components/object-set-table/subcomponents/default-cell-renderers/boolean-render.tsx
src/ui/components/object-set-table/subcomponents/default-cell-renderers/get-render-fn.ts
src/ui/components/object-set-table/types.ts

https://trello.com/c/Jc2kSYtW/1042-add-boolean-support-for-the-objectsettable
- Added boolean cells in the Object Set Table

feat: add boolean cells support

---

src/scalars/components/date-picker-field/date-picker-field.test.tsx

https://trello.com/c/9tLrr0kD/957-fix-the-failed-tests-after-update-from-the-core-dev
- src/scalars/components/date-picker-field/date-picker-field.test.tsx

test(scalars): fix the test date-picker

---

src/ui/components/data-entry/date-time-picker/__snapshots__/date-time-picker.test.tsx.snap
src/ui/components/data-entry/date-time-picker/date-time-picker.test.tsx

https://trello.com/c/9tLrr0kD/957-fix-the-failed-tests-after-update-from-the-core-dev
- Identify missing tests

test(scalars): add test for date-time-picker component

---

src/ui/components/object-set-table/examples/api-usage/api-usage.stories.tsx
src/ui/components/object-set-table/examples/api-usage/api-usage.tsx
src/ui/components/object-set-table/examples/api-usage/button.tsx
src/ui/components/object-set-table/hooks/useGlobalTableKeyEvents.tsx
src/ui/components/object-set-table/logic/public-table-api.ts
src/ui/components/object-set-table/logic/selection-manager.ts
src/ui/components/object-set-table/logic/table-api.ts
src/ui/components/object-set-table/logic/types.ts
src/ui/components/object-set-table/object-set-table.stories.tsx
src/ui/components/object-set-table/object-set-table.tsx
src/ui/components/object-set-table/subcomponents/header.tsx
src/ui/components/object-set-table/subcomponents/table-focus-trap.tsx
src/ui/components/object-set-table/subcomponents/table-provider/table-provider.tsx
src/ui/components/object-set-table/subcomponents/table-provider/table-reducer.tsx
src/ui/components/object-set-table/types.ts

https://trello.com/c/sh1Cb4qN/915-initialize-table-structure-and-basic-scaffolding
- Allow to use the public API programmatically outside the Table component
- Improve table documentation
- Added API usage example

Allow public table API usage

---

src/scalars/components/date-picker-field/date-picker-field.stories.tsx
src/scalars/components/date-time-picker-field/date-time-picker-field.stories.tsx
src/ui/components/data-entry/date-picker/date-picker.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker-content.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.tsx
src/ui/components/data-entry/time-picker/time-picker.stories.tsx

https://trello.com/c/7mHGBONQ/1047-enable-customization-of-component-styles
- Should apply the necessary changes to the DateTimeField component.

feat(scalars): add class for customize the date-time-picker-field

---

src/scalars/components/country-code-field/country-code-field.tsx
src/scalars/components/country-code-field/index.ts
src/scalars/components/country-code-field/types.ts
src/ui/components/data-entry/country-code-picker/__snapshots__/country-code-picker.test.tsx.snap
src/ui/components/data-entry/country-code-picker/country-code-picker.stories.tsx
src/ui/components/data-entry/country-code-picker/country-code-picker.test.tsx
src/ui/components/data-entry/country-code-picker/country-code-picker.tsx
src/ui/components/data-entry/country-code-picker/index.ts
src/ui/components/data-entry/country-code-picker/types.ts
src/ui/components/index.ts

https://trello.com/c/6TjyTETw/918-adapt-country-code-component-to-be-used-outside-of-the-form
- Should separate the types in two categories to be used outside and inside of the form.
- Should create the component variant to be used outside of the form.
- Should apply the new file structure in code (design system).
- Should create the new component stories.

feat(scalars & ui): Detach the Country Code component from the Form

---

src/scalars/components/number-field/number-field.stories.tsx
src/ui/components/data-entry/number-input/number-input.stories.tsx
src/ui/components/data-entry/number-input/number-input.tsx
src/ui/components/data-entry/number-input/types.ts

https://trello.com/c/rNiSUWdp
- Add diff status for number-field y number-input component. The idea is to show the differences depend on the viewMode

feat(scalars): feat add diff in number component

---

src/scalars/components/date-picker-field/__snapshots__/date-picker-field.test.tsx.snap
src/scalars/components/date-time-picker-field/__snapshots__/date-time-picker-field.test.tsx.snap
src/scalars/components/time-picker-field/__snapshots__/time-picker-field.test.tsx.snap
src/ui/components/data-entry/date-picker/__snapshots__/date-picker.test.tsx.snap
src/ui/components/data-entry/date-picker/date-picker.stories.tsx
src/ui/components/data-entry/date-picker/date-picker.tsx
src/ui/components/data-entry/date-time-picker/__snapshots__/date-time-picker.test.tsx.snap
src/ui/components/data-entry/date-time-picker/base-picker.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.tsx
src/ui/components/data-entry/time-picker/__snapshots__/time-picker.test.tsx.snap
src/ui/components/data-entry/time-picker/time-picker.stories.tsx
src/ui/components/data-entry/time-picker/time-picker.tsx

- No ticker
- Add the option to change the with of the input and also, add the option for change the with of the popover

fix(scalars) remove the fixed with in datepicker 

---

src/scalars/components/time-picker-field/time-picker-field.stories.tsx
src/ui/components/data-entry/input/splitted-input-diff.tsx
src/ui/components/data-entry/text-input/text-input-diff.tsx
src/ui/components/data-entry/time-picker/time-picker.stories.tsx
src/ui/components/data-entry/time-picker/time-picker.test.tsx
src/ui/components/data-entry/time-picker/time-picker.tsx

- Add differences for TimePickerField
- Add new test-cases for testing the new feature
- Should create a new status read only diff TimePickerField

feat(scalars): add time picker differences

---

src/scalars/components/date-picker-field/date-picker-field.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.test.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.tsx
src/ui/components/data-entry/date-time-picker/subcomponent/date-time-picker-diff.tsx
src/ui/components/data-entry/date-time-picker/use-date-time-picker.tsx

https://trello.com/c/nd38TjbM/1056-create-a-read-only-diff-status-for-the-datetimepicker-component
- Add differences for DateTimePickerField component
- Add test case to test new feat
- Should create a new status read only diff DateTimePickerFiled

feat(scalars): add diff for date-time-picker component

---

src/ui/components/object-set-table/examples/computed-columns/computed-columns.tsx
src/ui/components/object-set-table/examples/custom-rendering/custom-rendering.tsx
src/ui/components/object-set-table/object-set-table.stories.tsx

https://trello.com/c/sh1Cb4qN/915-initialize-table-structure-and-basic-scaffolding
- Ensure examples in stories are editable using args controls

fix: object set table stories control

---

src/ui/components/data-entry/amount-input/amount-input.tsx
src/ui/components/data-entry/number-input/number-input.stories.tsx
src/ui/components/data-entry/number-input/number-input.test.tsx
src/ui/components/data-entry/number-input/number-input.tsx
src/ui/components/data-entry/number-input/types.ts
src/ui/components/data-entry/number-input/use-number-input.ts
src/ui/components/data-entry/text-input/text-input-diff.tsx

- Fix the issue when number its bigger than MAX_SAFE_INTEGER and its not a big integer, show not increment or decrement

fix(scalars): fix the issues for increment and decrement

---

src/ui/components/data-entry/number-input/number-input.stories.tsx
src/ui/components/data-entry/number-input/types.ts
src/ui/components/data-entry/number-input/use-number-input.ts

-  Fix the the type props in number component

fix(scalars): fix the value and default props for number field

---

src/scalars/components/amount-field/amount-field.stories.tsx
src/ui/components/data-entry/amount-input/amount-input.stories.tsx
src/ui/components/data-entry/amount-input/subcomponents/fake-amount-diff.tsx
src/ui/components/data-entry/date-picker/date-picker.stories.tsx
src/ui/components/data-entry/date-time-picker/date-time-picker.stories.tsx
src/ui/components/data-entry/time-picker/time-picker.stories.tsx

- Show the correct color in the symbol when its in mixed viewMode
- Add missing props in the data entry component

fix(scalars): fix the symbol colors when values are the same

---

src/scalars/components/boolean-field/boolean-field.stories.tsx
src/scalars/components/date-time-picker-field/date-time-picker-field.stories.tsx
src/scalars/components/fragments/toggle-field/toggle-field.test.tsx
src/scalars/components/time-picker-field/time-picker-field.stories.tsx
src/ui/components/data-entry/checkbox/checkbox.stories.tsx
src/ui/components/data-entry/toggle/subcomponents/toogle-diff.tsx
src/ui/components/data-entry/toggle/toggle.stories.tsx
src/ui/components/data-entry/toggle/toggle.tsx

- https://trello.com/c/oxAOKsO1/1072-diff-status-comparison-stories-are-missing-in-multiples-components
-  Add missing stories for the boolean components, and add test for it

fix(scalars): add missing stories for boolean and date time component

---

src/scalars/components/amount-field/amount-currency-validations.ts
src/scalars/components/amount-field/amount-field-validations.ts
src/scalars/lib/value-cast.ts

Optional field. Submitting empty values.  The field should submit a null value.  "Please select a valid currency" error message is displayed. If the field currency its no required, should be submit a empty value for currency

fix(scalars): fix the validations in the currency

---

src/ui/components/object-set-table/examples/table-editing/table-editing.tsx
src/ui/components/object-set-table/subcomponents/default-cell-renderers/boolean-render.tsx
src/ui/components/object-set-table/subcomponents/default-cell-renderers/number-render.tsx
src/ui/components/object-set-table/subcomponents/default-cell-renderers/text-render.tsx

https://trello.com/c/sh1Cb4qN
- Fixed issue with column alignment

fix: column alignment

---

src/scalars/components/amount-field/amount-field.stories.tsx
src/ui/components/data-entry/amount-input/amount-input.stories.tsx

- Should update the story's name in the Storybook.

fix(scalars): update the name stories

---

src/scalars/components/amount-field/amount-field-validations.ts
src/scalars/components/amount-field/amount-field.stories.tsx
src/scalars/components/amount-field/amount-field.test.tsx
src/scalars/lib/value-cast.ts
src/ui/components/data-entry/amount-input/amount-input.stories.tsx
src/ui/components/data-entry/amount-input/amount-input.test.tsx
src/ui/components/data-entry/amount-input/subcomponents/fake-amount-diff.tsx
src/ui/components/data-entry/amount-input/types.ts
src/ui/components/data-entry/amount-input/use-amount-input.tsx

https://trello.com/c/iV03PjGR/757-9-amountfield
- Match the field in amount with the API

fix(scalars): match the name as the scalar api in connect

---

src/ui/components/object-set-table/object-set-table.stories.tsx
src/ui/components/object-set-table/types.ts

https://trello.com/c/sh1Cb4qN/915-initialize-table-structure-and-basic-scaffolding
- Added missing documentation about sorting

docs: add sorting props to the documentation

---

src/scalars/components/currency-code-field/currency-code-field.stories.tsx
src/ui/components/data-entry/currency-code-picker/currency-code-picker.stories.tsx

https://trello.com/c/Y2sFr9aM/1086-storybook-breaks-after-adding-a-currency-name
Update the storybook documentation with the currencies prop specifications. Add a better description for the necessary types in the Currency type

fix(scalars): add missing docs for currency

---

src/scalars/components/password-field/__snapshots__/password-field.test.tsx.snap
src/scalars/components/password-field/index.ts
src/scalars/components/password-field/password-field.stories.tsx
src/scalars/components/password-field/password-field.test.tsx
src/scalars/components/password-field/password-field.tsx
src/scalars/components/password-field/types.ts
src/scalars/lib/utils.ts
src/ui/components/data-entry/password-input/password-input.stories.tsx
src/ui/components/data-entry/password-input/password-input.test.tsx
src/ui/components/data-entry/password-input/password-input.tsx
src/ui/components/data-entry/password-input/types.ts
src/ui/components/data-entry/password-input/utils.ts

https://trello.com/c/HY0SrSNt/1079-17-password
- Adds PasswordField component
- Adds password format validation
- Adds related tests & stories

feat(scalars): adds PasswordField + password format validations

---

package.json
pnpm-lock.yaml
src/scalars/components/password-field/password-field.stories.tsx
src/scalars/components/password-field/password-field.tsx
src/scalars/components/password-field/types.ts
src/ui/components/data-entry/password-input/password-input.stories.tsx
src/ui/components/data-entry/password-input/password-input.tsx
src/ui/components/data-entry/password-input/password-strength.tsx
src/ui/components/data-entry/password-input/types.ts
src/ui/components/data-entry/password-input/utils.ts

https://trello.com/c/HY0SrSNt/1079-17-password
- Adds the PasswordStrength component

feat(ui): add PasswordStrength component

---

src/scalars/components/email-field/__snapshots__/email-field.test.tsx.snap
src/scalars/components/email-field/email-field.test.tsx
src/scalars/components/email-field/email-field.tsx
src/scalars/components/form/form.test.tsx
src/ui/components/data-entry/email-input/email-input.tsx

- Update the EmailField and Input Email with fixes applied in the following [PR](https://github.com/powerhouse-inc/document-engineering/pull/129)

fix(scalars): apply new aproach for matchFieldName in email

---

src/scalars/components/number-field/index.ts
src/scalars/components/number-field/number-field-validations.ts
src/scalars/components/number-field/number-field.tsx
src/scalars/components/number-field/types.ts
src/ui/components/data-entry/number-input/index.ts
src/ui/components/data-entry/number-input/number-input.tsx
src/ui/components/data-entry/number-input/types.ts
src/ui/components/index.ts
src/ui/components/object-set-table/subcomponents/default-cell-editors/number-editor.tsx

- https://trello.com/c/zytYL34Q/1099-numberfield-should-be-imported-from-scalars
- Should ensure that the NumberField is imported from scalars. Ensure that the NumberField props are properly export from scalars

fix(scalars): fix the import in the number inpunt and number field

---

src/ui/components/data-entry/email-input/email-input.tsx
src/ui/components/data-entry/email-input/subcomponents/email-input-diff.tsx

https://trello.com/b/iebIfrww/powerhouse
- Read-Only diff comparison. We should keep the label in case that its provided

fix(scalars): add label for diff comparison

---

src/ui/components/sidebar/__snapshots__/sidebar.test.tsx.snap
src/ui/components/sidebar/sidebar.stories.tsx
src/ui/components/sidebar/sidebar.test.tsx
src/ui/components/sidebar/sidebar.tsx
src/ui/components/sidebar/subcomponents/sidebar-header.tsx

https://trello.com/c/nRHvv42e/1142-make-the-sidebar-title-a-clickable-button
- Enables click functionality on the sidebar title, allowing developers to navigate or execute a custom action on click.

feat(scalars): make sidebar title clickable

---

src/ui/components/sidebar/__snapshots__/sidebar.test.tsx.snap
src/ui/components/sidebar/sidebar.stories.tsx
src/ui/components/sidebar/sidebar.test.tsx
src/ui/components/sidebar/sidebar.tsx
src/ui/components/sidebar/subcomponents/sidebar-content-area.tsx
src/ui/components/sidebar/subcomponents/sidebar-skeleton-item.tsx
src/ui/components/sidebar/subcomponents/sidebar-skeleton.tsx

https://trello.com/c/QauohZf2
- Add option to show a loading state in the sidebar
- Updated the docs

feat: add sidebar loading

---

src/ui/components/data-entry/file-input/__snapshots__/file-input.test.tsx.snap
src/ui/components/data-entry/file-input/file-input.test.tsx
src/ui/components/data-entry/file-input/file-input.tsx

https://trello.com/c/bw7e04hI/1077-15-file
- Should the field reject attempts to upload multiple files simultaneously.

feat(scalars): add function onrealod and test for it

---

src/scalars/graphql/File.ts

https://trello.com/c/bw7e04hI/1077-15-file
- Should add the component to the Scalar Testing repo . Fix the error in the export in the Scalar type

fix(scalars): fix the error in the scalar export

---

src/scalars/components/file-field/file-field.stories.tsx
src/ui/components/data-entry/file-input/file-input.stories.tsx
src/ui/components/data-entry/file-input/file-input.test.tsx
src/ui/components/data-entry/file-input/file-input.tsx
src/ui/components/data-entry/file-input/sub-components/file-upload-item.tsx
src/ui/components/data-entry/file-input/types.ts
src/ui/components/data-entry/file-input/utils.ts

https://trello.com/c/vERepv6Q/1097-implement-preview-functionality-for-the-file-component
- Should create a Preview component

feat(scalars): add preview option for preview documents

---

src/ui/components/data-entry/file-input/file-input.tsx
src/ui/components/data-entry/file-input/sub-components/file-upload-item.tsx
src/ui/components/data-entry/file-input/useUploadFile.ts

https://trello.com/c/vERepv6Q/1097-implement-preview-functionality-for-the-file-component
- Should the preview component open a system viewer.

feat(scalars): add logic for dialog to show the preview

---

src/ui/components/data-entry/file-input/sub-components/preview-image.tsx

https://trello.com/c/vERepv6Q/1097-implement-preview-functionality-for-the-file-component
-  Should the component render and display previews for Image

feat(scalars): add preview component for image

---

src/scalars/components/phone-number-field/phone-number-field.tsx

https://trello.com/c/wvGNq1K4/1120-13-phonenumber
- Should validate the phone number format. (E.164 spec)

feat(scalars): add phone number validation

---

src/scalars/components/amount-field/__snapshots__/amount-field.test.tsx.snap
src/scalars/components/amount-field/amount-field.stories.tsx
src/scalars/components/number-field/__snapshots__/number-field.test.tsx.snap
src/scalars/components/number-field/number-field.stories.tsx
src/scalars/components/number-field/number-field.test.tsx
src/ui/components/data-entry/amount-input/__snapshots__/amount-input.test.tsx.snap
src/ui/components/data-entry/amount-input/amount-input.stories.tsx
src/ui/components/data-entry/amount-input/amount-input.tsx
src/ui/components/data-entry/number-input/__snapshots__/number-input.test.tsx.snap
src/ui/components/data-entry/number-input/number-input.stories.tsx
src/ui/components/data-entry/number-input/number-input.test.tsx
src/ui/components/data-entry/number-input/number-input.tsx
src/ui/components/data-entry/number-input/types.ts

https://trello.com/c/vEINL1Gh/1161-make-the-increment-decrement-carets-configurable
- Should add **enableStepCarets** prop. Disable by default.

feat(scalars): make-the-increment-decrement-carets-configurable

---

src/ui/components/data-entry/file-input/docs/file-upload-item.mdx
src/ui/components/data-entry/file-input/examples/file-upload-item-example.stories.tsx
src/ui/components/data-entry/file-input/examples/file-upload-item-example.tsx
src/ui/components/data-entry/file-input/examples/index.ts

https://trello.com/c/vERepv6Q/1097-implement-preview-functionality-for-the-file-component
- Improve the docs for FileUpload component that show state of loading file

docs(scalars): improve the docs for the preview

---

src/table/logic/table-api.ts

https://trello.com/c/GUb4sSsU
Prevent saving empty values when inserting in the insertion row

feat: prevent adding using empty values

---

src/table/docs/sorting.mdx

https://trello.com/c/GUb4sSsU
Add documentation about the `SortableColumnContext` in the sort docs page

docs(table): add documentation of the sortable column context

---

src/ui/components/sidebar/sidebar.stories.tsx
src/ui/components/sidebar/sidebar.test.tsx
src/ui/components/sidebar/sidebar.tsx
src/ui/components/sidebar/subcomponents/sidebar-provider/sidebar-provider.tsx
src/ui/components/sidebar/subcomponents/sidebar-provider/sidebar-reducer.tsx
src/ui/components/sidebar/types.ts
src/ui/components/sidebar/utils.ts

https://trello.com/c/xYTMIvAs/1153-make-the-sidebar-root-nodes-movable
- Improve types (remove "none" from NodeSortType)
- Improve logic related to nodes sorting
- Improve the story variant and controls related to nodes sorting

fix(sidebar): improve types, logic, controls and story variant related to nodes sorting

---

src/scalars/components/file-field/file-field.stories.tsx
src/scalars/components/file-field/file-field.tsx
src/ui/components/data-entry/file-input/file-input.stories.tsx
src/ui/components/data-entry/file-input/file-input.tsx
src/ui/components/data-entry/file-input/types.ts
src/ui/components/data-entry/file-input/useUploadFile.ts
src/ui/components/data-entry/file-input/utils.ts

- https://trello.com/c/bw7e04hI/1077-15-file
- Add props to convert the File into base64
- Add new functions for convert base64 to File to handle the preview
- Add helpers functions for validate and operate file in base64
- Add value the file conventions in base64

feat(file): add props for convert file to base64

---

src/table/components/cells/render-cell/render-cell.tsx
src/table/components/cells/render-cell/use-cell-logic.ts
src/table/components/default-cell-editors/country-editor.tsx
src/table/components/default-cell-renderers/country-render.tsx
src/table/components/table-focus-trap.tsx
src/table/examples/custom-cell-editors/custom-cell-editors.tsx
src/table/examples/events/events.tsx
src/table/examples/table-editing/table-editing.tsx
src/table/table/mock-data.ts

https://trello.com/c/7Q389yX6
This PR enhances the table system with improved country cell editing capabilities and better focus management. The changes include:
- Enhanced country cell editor with better value handling and type safety
- Improved country cell renderer with additional display options
- Updated table focus trap functionality for better keyboard navigation
- Refined cell rendering logic with improved state management
- Updated table editing examples to showcase new functionality
- Enhanced mock data for better testing scenarios
The improvements focus on providing a more robust and user-friendly table editing experience, particularly for country-related data fields.

feat(table): enhance country cell editing and focus management
